9 25 1
shinichiromasuo/study-laravel pull request #1
Opened 2018-09-26 07:58 UTC by shinichiromasuo

先ほどの件を改善する目的でのテストしてみました。

2018-09-26 09:10 UTC, ngmy commented on src/app/Http/Controllers/HelloController.php
> +  public function index(Request $request, Response $response) {
インデントはタブではなくスペース4個にしてください。

PHPプロジェクトではインデントはスペース4つと覚えておいてください。
（PHPの場合。他の言語は他の言語のデファクトスタンダードに従ってください。）

PHPにはPSR-2というデファクトスタンダードのコーディング規約があって、
それがスペース4個と決めてます。
Laravelもリネットもこれに従っています。

2018-09-26 09:14 UTC, ngmy commented on src/app/Http/Controllers/HelloController.php
> +`	margin:-50px 0px -120px 0px; }
先頭の「`」って何ですか？
typo？

2018-09-26 09:15 UTC, ngmy commented on src/app/Http/Controllers/HelloController.php
> +
最後の空行不要なので消しといてください。

2018-09-26 09:18 UTC, ngmy requested changes
確認おねがいします

2018-09-27 01:23 UTC, shinichiromasuo commented on src/app/Http/Controllers/HelloController.php
> +  public function index(Request $request, Response $response) {
承知しました！
有難うございます！

> インデントはタブではなくスペース4個にしてください。
> 
> PHPプロジェクトではインデントはスペース4つと覚えておいてください。
> （PHPの場合。他の言語は他の言語のデファクトスタンダードに従ってください。）
> 
> PHPにはPSR-2というデファクトスタンダードのコーディング規約があって、
> それがスペース4個と決めてます。
> Laravelもリネットもこれに従っています。

2018-09-27 01:23 UTC, shinichiromasuo commented on src/app/Http/Controllers/HelloController.php
> +`	margin:-50px 0px -120px 0px; }
すいませんtypoです、

2018-09-27 01:32 UTC, shinichiromasuo commented
review 有難うございます直しました！

2018-09-27 02:02 UTC, ngmy commented on src/app/Http/Controllers/HelloController.php
> +  public function index(Request $request, Response $response) {
ここインデントがおかしいです。

正：スペース4個
今：スペース2個

2018-09-27 02:02 UTC, ngmy commented on src/app/Http/Controllers/HelloController.php
> +$html = <<<EOF
この行、インデントがおかしいです。

ここインデントがおかしいです。

正：インデント2つ（＝スペース8個）
今：スペース0個

2018-09-27 02:04 UTC, ngmy commented on src/app/Http/Controllers/HelloController.php
> +    $response->setContent($html);
この行、インデントがおかしいです。

正：スペース8個（インデント2個）
今：スペース4個

2018-09-27 02:04 UTC, ngmy commented on src/app/Http/Controllers/HelloController.php
> +    return $response;
この行、インデントがおかしいです。

正：スペース8個（インデント2個）
今：スペース4個

2018-09-27 02:04 UTC, ngmy commented on src/app/Http/Controllers/HelloController.php
> +	}
この行、インデントがタブのままです。

2018-09-27 02:06 UTC, ngmy commented on src/app/Http/Controllers/HelloController.php
> +  public function index(Request $request, Response $response) {
function の `{` は同じ行ではなく次の行に書いてください

ダメ：
```
function hoge() {

}
```

正解：
```
function hoge()
{

}
```

2018-09-27 02:07 UTC, ngmy requested changes
まだインデントがおかしいです。
確認お願いします！

2018-09-27 07:50 UTC, ngmy approved these changes
LGTM

2018-09-27 07:50 UTC, merged