第７章　RESTfullサービス／セッション／認証／テスト
shinichiromasuo/study-laravel pull request #10
Opened 2018-10-12 06:58 UTC by shinichiromasuo

2018-10-16 04:37 UTC, ngmy commented on src/app/Http/Controllers/RestappController.php
> +<?php
ここまでの理解度チェックって意味で、このRestappControllerを改造してresourcefulなサービスを作って見てください。

| 画面名 | コントローラ・アクション | 内容| 備考 |
| --- | --- | --- | --- | 
| 一覧画面 | `RestappController@index` | 全てのリソースを一覧で表示する。個別に表示画面へのリンク付き | 今あるものにテンプレートを追加する必要するイメージ |
| 作成画面 | `RestappController@create` | 新規リソースを作成するためのフォーム | 既にあるものでOK |
| 表示画面 | `RestappController@show`| 既存リソースの内容を表示するための画面、更新画面へのリンク、削除ボタン | |
| 更新画面 | `RestappController@update` | 既存リソースを更新するためのフォーム | |
| 作成処理 | `RestappController@store` | 新規リソースの作成処理 | 今あるものでOK |
| 更新処理 | `RestappController@update` | 既存リソースの更新処理 | |
| 削除処理 | `RestappController@destroy` | 既存リソースの削除処理 | |

2018-10-16 04:38 UTC, ngmy reviewed
理解度チェックって意味でやってみてください

2018-10-18 01:47 UTC, ngmy commented on src/app/Exceptions/Handler.php
> +        if($this->isHttpException($exception)){
全体的にphpcsかけてる？

2018-10-18 01:47 UTC, ngmy commented on src/app/Http/Controllers/RestappController.php
> +        if($item == null) {
nullの判定は`is_null`を使ってください。

2018-10-18 01:51 UTC, ngmy commented on src/app/Exceptions/Handler.php
> +            if($exception->getStatusCode() == 404) {
```
if($this->isHttpException($exception)){
　　　　 if($exception->getStatusCode() == 404) {
```

が冗長だと思う。

ヒント：
404のときは`Exception`を継承した特別な例外クラスがくるので、$exceptionがそのインスタンスがどうかを判定すればifが1個で良いと思います。

2018-10-18 01:52 UTC, ngmy requested changes
コメントしました。
あとバリデーションも実装してねー

2018-10-18 04:57 UTC, shinichiromasuo commented on src/app/Exceptions/Handler.php
> -        if($this->isHttpException($exception)){
/resource/view/にerrorsディレクトリを作り404.bladeファイルを作れば自動で404エラーが出た時にいけます！

2018-10-18 07:59 UTC, ngmy commented on src/app/Restdata.php
> +        'url' => 'required|between:1,255'
Laravelのバリデーションルールをみてみてください
urlの場合有効なURLであることを検証するバリデーションがあります

2018-10-18 08:36 UTC, shinichiromasuo commented on src/app/Restdata.php
> +        'url' => 'required|between:1,255|active_url'
URLの検証を追加しました！

2018-10-18 09:02 UTC, ngmy approved these changes

2018-10-18 09:02 UTC, merged