3-1 PHPテンプレートの利用
shinichiromasuo/study-laravel pull request #2
Opened 2018-09-27 08:49 UTC by shinichiromasuo

2018-09-30 11:13 UTC, shinichiromasuo commented
３−5の題名はタイプミスです。

2018-10-01 04:31 UTC, ngmy commented on src/app/Http/Controllers/HelloComposer.php
> +class Hellovomposer
クラス名typoしてるっぽいけど、Composerで読み込めてる？

2018-10-01 04:35 UTC, ngmy requested changes
確認お願いします！

2018-10-01 05:22 UTC, shinichiromasuo commented
修正しましたので、確認よろしくお願いします！

2018-10-01 05:32 UTC, ngmy approved these changes
LGTM

2018-10-01 05:32 UTC, merged