4-1ミドルウェアの利用
shinichiromasuo/study-laravel pull request #3
Opened 2018-10-01 07:07 UTC by shinichiromasuo

2018-10-02 06:35 UTC, ngmy commented on src/app/Http/Controllers/HelloController.php
> +        {
制御構造の括弧は同じ行に書いてください

see: PSR-2
http://www.infiniteloop.co.jp/docs/psr/psr-2-coding-style-guide.html

2018-10-02 06:37 UTC, ngmy commented on src/app/Http/Kernel.php
> +
このdiffはいったい。。？

2018-10-02 06:38 UTC, ngmy commented on src/routes/web.php
> +use App\Http\Middleware\HelloMiddleware;
これはuseして何に使ってるんだろうか？
参考書でそうなってるのかも。あとで聞きます。

2018-10-02 06:41 UTC, ngmy commented on src/app/Http/Kernel.php
> +        'helo' => [
typoしてない？

2018-10-02 06:41 UTC, ngmy requested changes
確認お願いします

2018-10-02 06:45 UTC, shinichiromasuo commented
有難うございます！
承知しました！

2018-10-03 08:19 UTC, ngmy approved these changes
LGMT

2018-10-03 08:19 UTC, merged